version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: TBSA
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tbsa_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tbsa_password}
      POSTGRES_DB: ${POSTGRES_DB:-tbsa}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-tbsa_admin} -d ${POSTGRES_DB:-tbsa}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
